apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  labels:
    app: xxx
spec:
  containers:
    - name: dnsutils
      image: ebpf-test
      imagePullPolicy: IfNotPresent
      command: [ "sleep","3600" ]

